import type { Book } from "./types";

function line(
  id: string,
  title: string,
  author: string,
  section: string,
  citation: string,
): Book {
  return {
    id: `book-marco-${id}`,
    title,
    author,
    place: "to-get",
    note: `Marco Andrade, 29 September 2026. ${section}. ${citation}`,
  };
}

export function marcoShelf(): Book[] {
  return [
    line(
      "startup-pitch",
      "How to Win a Startup Pitch Competition: Successful Insights from a Topnotch Judge for Boosting Your Startup",
      "Lance Eliot",
      "Books for your business",
      "Title and author as given. No place or year was given.",
    ),
    line(
      "origin-of-the-universe",
      "The Origin of the Universe",
      "John D. Barrow",
      "Background science for understanding remote viewing",
      "New York: Basic Books, 1994.",
    ),
    line(
      "stalking-the-wild-pendulum",
      "Stalking the Wild Pendulum: On the Mechanics of Consciousness",
      "Itzhak Bentov",
      "Background science for understanding remote viewing",
      "Rochester, VT: Destiny Books, reprint 1988.",
    ),
    line(
      "bohm-nonlocality",
      "On the Intuitive Understanding of Nonlocality as Implied by Quantom Theory",
      "D. Bohm and B.J. Hiley",
      "Background science for understanding remote viewing",
      "Foundations of Physics 5 (1975): 93-109. The title is spelled Quantom, as written.",
    ),
    line(
      "six-easy-pieces",
      "Six Easy Pieces: Essentials of Physics Explained by its Most Brilliant Teacher",
      "Richard P. Feynman, with introduction by Paul Davies",
      "Background science for understanding remote viewing",
      "New York: Perseus Books, 1996.",
    ),
    line(
      "one-two-three-infinity",
      "One Two Three...Infinity: Facts and Speculations of Science",
      "George Gamow",
      "Background science for understanding remote viewing",
      "New York: Dover Publications, 1988.",
    ),
    line(
      "holotropic-mind",
      "The Holotropic Mind: Three Levels of Human Consciousness and How They Shape Our Lives",
      "Stanislavsky Grof, with Hal Zina Bennett",
      "Background science for understanding remote viewing",
      "San Francisco: HarperSanFrancisco, 1993. The given name is spelled Stanislavsky, as written.",
    ),
    line(
      "psychic-war",
      "The Psychic War: Parapsychology in Espionage---and Beyond",
      "Elmar R. Gruber",
      "Background science for understanding remote viewing",
      "New York: Blandford Publishing, 1999.",
    ),
    line(
      "occult-chemistry",
      "Occult Chemistry: Investigations by Clairvoyant Magnification into the Structure of the Atoms of the Periodic Table and Some Compounds",
      "C. W. Leadbeater and Annie Besant",
      "Background science for understanding remote viewing",
      "Whitefish, MT: Kessinger Publishing, 1997.",
    ),
    line(
      "psychic-discoveries",
      "Psychic Discoveries behind the Iron Curtain",
      "Sheila Ostrander and Lynn Schroeder",
      "Background science for understanding remote viewing",
      "New York: Prentice-Hall, 1984.",
    ),
    line(
      "walker-foundations",
      "Foundations of Paraphysical and Parapsychological Phenomena",
      "E. H. Walker",
      "Background science for understanding remote viewing",
      "In Quantum Physics and Parapsychology, edited by Laura Oteri, 1-53. New York: Parapsychological Association, Inc, 1975.",
    ),
    line(
      "geons-black-holes",
      "Geons, Black Holes & Quantum Foam: A Life in Physics",
      "John Archibald Wheeler, with Ken Ford",
      "Background science for understanding remote viewing",
      "New York: W.W. Norton, 2000.",
    ),
    line(
      "meeting-of-science-and-spirit",
      "The Meeting of Science and Spirit: Guidelines for a New Age",
      "John White",
      "Background science for understanding remote viewing",
      "New York: Paragon House Publishers, 1990.",
    ),
    line(
      "parallel-universes",
      "Parallel Universes: The Search for Other Worlds",
      "Fred Alan Wolf",
      "Background science for understanding remote viewing",
      "New York: Simon & Schuster, 1990.",
    ),
    line(
      "information-transmission",
      "Information Transmission Under Conditions of Sensory Shielding",
      "Harold E. Puthoff and Russell Targ",
      "The scientific history of remote viewing (circa 1972-1993)",
      "Proceedings of the IEEE (January 1975): 12-19.",
    ),
    line(
      "perceptual-augmentation",
      "Perceptual Augmentation Techniques: Part Two---Research Report",
      "Harold E. Puthoff and Russell Targ",
      "The scientific history of remote viewing (circa 1972-1993)",
      "The list gave this citation twice. First: Standford Research Institute Final Report (December 1, 1975). Later, under scientific and technical resources, the author was spelled Puthofdf and the institute Stanford Research Institute. Same title and date. Entered once.",
    ),
    line(
      "perceptual-channel",
      "A Perceptual Channel for Information Transfer over Kilometer Distances: Historical Perspective and Recent Research",
      "Harold E. Puthoff and Russell Targ",
      "The scientific history of remote viewing (circa 1972-1993)",
      "Proceedings of the IEEE (March 1976): 329-354.",
    ),
    line(
      "mind-race",
      "The Mind Race: Understanding and Using Psychic Abilities",
      "Russell Targ and Keith Harary",
      "The scientific history of remote viewing (circa 1972-1993)",
      "New York: Ballantine Books 1985.",
    ),
    line(
      "miracles-of-mind",
      "Miracles of Mind: Exploring Nonlocal Consciousness and Spiritual Healing",
      "Russell Targ and Jane Katra",
      "The scientific history of remote viewing (circa 1972-1993)",
      "Novato, CA: New World Library 1999.",
    ),
    line(
      "mind-reach",
      "Mind-Reach: Scientists Look at Physic Abilities",
      "Russell Targ and Harold Puthoff",
      "The scientific history of remote viewing (circa 1972-1993)",
      "New York: Delacorte Press, 1977. The title says Physic, as written.",
    ),
    line(
      "mind-at-large",
      "Mind at Large: IEEE Symposia on the Nature of Extrasensory Perception",
      "Charles T. Tart, Harold E. Puthoff, and Russell Targ, eds.",
      "The scientific history of remote viewing (circa 1972-1993)",
      "Charlottesville, VA: Hampton Roads Publishing Company, 2002.",
    ),
    line(
      "does-psi-exist",
      "Does PSI Exist? Replicable Evidence for an Anomalous Process of Information Transfer",
      "Daryl J. Bem and Charles Honorton",
      "Scientific and technical resources and references",
      "Psychological Bulletin 115 (1994): 4-18.",
    ),
    line(
      "amsterdam-ganzfeld",
      "The Amsterdam Ganzfeld Series III & IV: Target Clip Emotionally, Effect Sizes, and Openness",
      "Dick J. Bierman",
      "Scientific and technical resources and references",
      "In Proceedings of Presented Papers: The 38th Annual Parapsychological Association Convention, edited by N.L. Zingrone, 27-37. Petaluma, CA: Parapsychological Association, Inc., 1995.",
    ),
    line(
      "autoganzfeld-ii",
      "Autoganzfeld II: The First 100 Sessions",
      "Richard Broughton and Cheryl Alexander",
      "Scientific and technical resources and references",
      "In Proceedings of Presented Papers: The 38th Annual Parapsychological Association Convention, edited by N.L. Zingrone 53-61. Petaluma, CA: Parapsychological Association, Inc., 1975.",
    ),
    line(
      "ac-technical-trials",
      "AC Technical Trials: Inspiration for the Target Entropy Concept",
      "Edwin C. May",
      "Scientific and technical resources and references",
      "SAIC Technical Report (May 26, 1995).",
    ),
    line(
      "feedback-considerations",
      "Feedback Considerations in Anomalous Cognition Experiments",
      "Edwin C. May, Nevin D. Lantz, and Tom Piantineda",
      "Scientific and technical resources and references",
      "Cognitive Sciences Laboratory Technical Report (November 29, 1994). The third name is spelled Piantineda, as written.",
    ),
    line(
      "sri-review-1973-1988",
      "Review of the Psychoenergetic Research Conducted at SRI International (1973-1988)",
      "Edwin C. May, J. M. Utts, V. V. Trask, W.W. Luke, T.J. Frivold, and B.S. Humphrey",
      "Scientific and technical resources and references",
      "SRI International Technical Report (March 1989). The list wrote May Edwin C., with no comma after May.",
    ),
    line(
      "sender-no-sender",
      "Comparison of the Sender/No Sender Condition in the Ganzfeld",
      "Robert L. Morris, Kathy Dalton, Deborah Delanoy, and Caroline Watt",
      "Scientific and technical resources and references",
      "In Proceedings of Presented Papers: The 38th Annual Parapsychological Association Convention, edited by N.L. Zingrone, 244-259. Petaluma, CA: Parapsychological Association, Inc., 1995.",
    ),
    line(
      "seventh-sense",
      "The Seventh Sense: The Secrets of Remote Viewing as Told by a \"Psychic Spy\" for the U.S. Military",
      "Lyn Buchanan",
      "The art and science of remote viewing. Remote viewing accounts",
      "New York: Paraview Pocket Books, 2003.",
    ),
    line(
      "stargate-chronicles",
      "The Stargate Chronicles: Memoirs of a Psychic Spy",
      "Joseph McMoneagle",
      "The art and science of remote viewing. Remote viewing accounts",
      "Charlottesville, VA: Hampton Roads Publishing Company, 2002.",
    ),
    line(
      "mind-trek",
      "Mind Trek: Exploring Consciousness, Time, and Space Through Remote Viewing",
      "Joseph McMoneagle",
      "The art and science of remote viewing. Remote viewing accounts",
      "Charlottesville, VA: Hampton Roads Publishing Company, 1993, 1997.",
    ),
    line(
      "ultimate-time-machine",
      "The Ultimate Time Machine: A Remote Viewer's Perception of Time, and Predictions for the New Millennium",
      "Joseph McMoneagle",
      "The art and science of remote viewing. Remote viewing accounts",
      "Charlottesville, VA: Hampton Roads Publishing Company, 1988.",
    ),
    line(
      "psychic-warrior",
      "Psychic Warrior: Inside the CIA's Stargate Program: The True Story of a Soldier's Espionage and Awakening",
      "David Morehouse",
      "The art and science of remote viewing. Remote viewing accounts",
      "New York: St. Martin's Press, 1996. This is not the Remote Viewing title already on the read shelf.",
    ),
    line(
      "rifat-remote-viewing",
      "Remote Viewing: What It Is, Who Uses It, and How to Do It",
      "Tim Rifat",
      "The art and science of remote viewing. Remote viewing accounts",
      "London: Vision Paperbacks, 2003.",
    ),
    line(
      "remote-viewers-schnabel",
      "Remote Viewers: The Secret History of America's Psychic Spies",
      "Jim Schnabel",
      "The art and science of remote viewing. Remote viewing accounts",
      "New York: Dell Publishing, 1997.",
    ),
    line(
      "walking-meditation",
      "Walking Meditation",
      "Nguyen Anh-Huong and Thich Nhat Hanh",
      "The art and science of remote viewing. Meditation",
      "Boulder, CO: Sounds True, 2006.",
    ),
    line(
      "meditation-for-beginners",
      "Meditation for Beginners: Six Guided Meditations for Insight, Inner Clarity, and Cultivating a Compassionate Heart",
      "Jack Kornfield",
      "The art and science of remote viewing. Meditation",
      "Boulder, CO: Sounds True 2004.",
    ),
    line(
      "natural-radiance",
      "Natural Radiance: Awakening to Your Great Perfection",
      "Lama Surya Days",
      "The art and science of remote viewing. Meditation",
      "Boulder, CO: Sounds True, 2005. The name is spelled Lama Surya Days, as written.",
    ),
    line(
      "yoga-nidra",
      "Yoga Nidra: Awaken to Unqualified Presence through Traditional Mind-Body Practices",
      "Richard Miller",
      "The art and science of remote viewing. Meditation",
      "Boulder, CO: Sounds True, 2005.",
    ),
    line(
      "tibetan-yogas",
      "The Tibetan Yogas of Dream and Sleep",
      "Tenzin Wangyal Rinpoche",
      "The art and science of remote viewing. Meditation",
      "New York: Snow Lion Publications, 1998.",
    ),
    line(
      "sitting",
      "Sitting: A Guide to Buddhist Meditation",
      "Diana St. Ruth",
      "The art and science of remote viewing. Meditation",
      "New York: Penguin Group, 1998.",
    ),
    line(
      "zen-mind",
      "Zen Mind, Beginner's Mind: Informal Talks on Zen Meditation and Practice",
      "Shunryu Suzuki",
      "The art and science of remote viewing. Meditation",
      "New York: John Weatherhill, 1970.",
    ),
    line(
      "meditation-new-york-minute",
      "Meditation in a New York Minute: Super Calm for the Super Busy",
      "Mark Thornton",
      "The art and science of remote viewing. Meditation",
      "Boulder, CO: Sounds True, 2006.",
    ),
    line(
      "shambhala",
      "Shambhala: The Sacred Path of the Warrior",
      "Chögyam Trungpa",
      "The art and science of remote viewing. Meditation",
      "Boston: Shambhala Publications, 1984.",
    ),
    line(
      "flatland",
      "Flatland",
      "E. A. Abbott",
      "General reading on psychology, physics, metaphysics and the like",
      "Princeton University Press, 1884.",
    ),
    line(
      "bell-hidden-variables",
      "On the Problem of Hidden Variables In Quantum Theory",
      "J.S. Bell",
      "General reading on psychology, physics, metaphysics and the like",
      "Review of Modern Physics 38 (1966): 447-452.",
    ),
    line(
      "time-travel",
      "Time Travel: A New Perspective",
      "J.H. Brennan",
      "General reading on psychology, physics, metaphysics and the like",
      "St. Paul, MN: Llewellyn Publications, 1997. The list had no space after J.H.",
    ),
    line(
      "tao-of-physics",
      "The Tao of Physics",
      "Fritof Capra",
      "General reading on psychology, physics, metaphysics and the like",
      "Boston: Shambhala Publications, 1984, 1999. The given name is spelled Fritof, as written.",
    ),
    line(
      "mapping-the-mind",
      "Mapping the Mind",
      "Rita Carter",
      "General reading on psychology, physics, metaphysics and the like",
      "Berkeley: University of California Press, 1998.",
    ),
    line(
      "states-of-mind",
      "States of Mind. New Discoveries about How Our Brains Make Us Who We Are",
      "Roberta Conlan, ed.",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: John Wiley & Sons, 2001.",
    ),
    line(
      "about-time",
      "About Time: Einstein's Unfinished Revolution",
      "Paul Davies",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Simon & Schuster, 1996.",
    ),
    line(
      "fifth-miracle",
      "The 5th Miracle: The Search for the Origin and Meaning of Life",
      "Paul Davies",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Simon & Schuster, 2000.",
    ),
    line(
      "last-three-minutes",
      "The Last Three Minutes: Conjectures about the Ultimate Fate of the Universe",
      "Paul Davies",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Perseus Books, 1994.",
    ),
    line(
      "mind-of-god",
      "The Mind of God: The Scientific Basis of a Rational World",
      "Paul Davies",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Prentice-Hall, 1974.",
    ),
    line(
      "executive-esp",
      "Executive ESP",
      "D. Dean, J. Mihalasky, S. Ostrander, and L. Schroeder",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Prentice-Hall, 1974.",
    ),
    line(
      "world-as-i-found-it",
      "The World as I Found It",
      "Bruce Duffy",
      "General reading on psychology, physics, metaphysics and the like",
      "Boston: Houghton Mifflin, 1988.",
    ),
    line(
      "universe-of-consciousness",
      "A Universe of Consciousness: How Matter Becomes Imagination",
      "Gerald M. Edelman and Giulio Tononi",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Basic Books, 2000.",
    ),
    line(
      "drawing-on-the-right-side",
      "Drawing on the Right Side of the Brain",
      "Betty Edwards",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: St. Martin's Press, 1979.",
    ),
    line(
      "cognitive-dissonance",
      "A Theory of Cognitive Dissonance",
      "Leon Festinger",
      "General reading on psychology, physics, metaphysics and the like",
      "Palo Alto, CA: Stanford University Press, 1957.",
    ),
    line(
      "minds-new-science",
      "The Mind's New Science: A History of the Cognitive Revolution",
      "Howard Gardner",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Basic Books, 1987.",
    ),
    line(
      "natures-mind",
      "Nature's Mind: The Biological Roots of Thinking, Emotions, Sexuality, Language, and Intelligence",
      "Michael S. Gazzaniga",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Basic Books 1994.",
    ),
    line(
      "tipping-point",
      "The Tipping Point: How Little Things Can Make a Big Difference",
      "Malcolm Gladwell",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Little, Brown and Company, 2000.",
    ),
    line(
      "when-the-impossible-happens",
      "When the Impossible Happens: Adventures in Non-ordinary Realities",
      "Stanislov Grof",
      "General reading on psychology, physics, metaphysics and the like",
      "Boulder, CO: Sounds True, 2006. The given name is spelled Stanislov, as written.",
    ),
    line(
      "brief-history-of-time",
      "A Brief History of Time",
      "Stephen Hawking",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Bantam Books, 1988.",
    ),
    line(
      "universe-in-a-nutshell",
      "The Universe in a Nutshell",
      "Stephen Hawking",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Bantam Book, 2001. The publisher is spelled Bantam Book, as written.",
    ),
    line(
      "dreaming-as-delirium",
      "Dreaming as Delirium: How the Brain Goes Out of Its Mind",
      "J. Allan Hobson",
      "General reading on psychology, physics, metaphysics and the like",
      "Cambridge, MA: MIT Press, 1999.",
    ),
    line(
      "eureka",
      "Eureka! Scientific Breakthroughs That Changed the World",
      "Leslie Allan Horvitz",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: John Wiley & Sons, 2002.",
    ),
    line(
      "realm-of-the-nebulae",
      "The Realm of the Nebulae",
      "Edwin Hubble",
      "General reading on psychology, physics, metaphysics and the like",
      "New Haven, CT: Yale University Press, 1935, reissue 1983.",
    ),
    line(
      "margins-of-reality",
      "Margins of Reality: The Role of Consciousness in the Physical World",
      "Robert G. Jahn and Brenda J. Dunne",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Harvest Books, 1989.",
    ),
    line(
      "palaces-of-memory",
      "In the Palaces of Memory: How We Build the Worlds Inside Our Heads",
      "George Johnson",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Alfred A. Knopf, 1991.",
    ),
    line(
      "cook-from-your-heart",
      "Cook from Your Heart: Recipes for Transformation",
      "Alice Louise Karow",
      "General reading on psychology, physics, metaphysics and the like",
      "Philadelphia: XLibris, 2006.",
    ),
    line(
      "chemistry-of-success",
      "The Chemistry of Success: 6 Secrets of Peak Performance",
      "Susan M. Lark and James A. Richards",
      "General reading on psychology, physics, metaphysics and the like",
      "Berkeley, CA: Bay Books, 1999.",
    ),
    line(
      "lloyd-objective-events",
      "Objective Events in the Brain Correlating with Psychic Phenomena",
      "D.H. Lloyd",
      "General reading on psychology, physics, metaphysics and the like",
      "New Horizons 1 (1973): 69-75.",
    ),
    line(
      "spirit-of-science",
      "The Spirit of Science: From Experiment to Experience",
      "David Lorimer, ed.",
      "General reading on psychology, physics, metaphysics and the like",
      "Edinburgh: Floris Books, 1998.",
    ),
    line(
      "synapses-circuits",
      "Synapses, Circuits, and the Beginnings of Memory",
      "Gary Lynch",
      "General reading on psychology, physics, metaphysics and the like",
      "Cambridge, MA: MIT Press, 1986.",
    ),
    line(
      "faster-than-light",
      "Faster Than the Speed of Light: The Story of a Scientific Speculation",
      "João Maguejio",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Perseus Books, 2004. The surname is spelled Maguejio, as written.",
    ),
    line(
      "to-infinity-and-beyond",
      "To Infinity and Beyond: A Cultural History of the Infinite",
      "Eli Maor",
      "General reading on psychology, physics, metaphysics and the like",
      "Princeton, NJ: Princeton University Press, 1991.",
    ),
    line(
      "men-against-fire",
      "Men Against Fire: The Problem of the Battle Command in Future War",
      "Colonel S. L. A. Marshall",
      "General reading on psychology, physics, metaphysics and the like",
      "Gloucester, MA: Peter Smith Books, 1978.",
    ),
    line(
      "embodiments-of-mind",
      "Embodiments of Mind",
      "Warren S. McCulloch",
      "General reading on psychology, physics, metaphysics and the like",
      "Cambridge, MA: MIT Press, 1988.",
    ),
    line(
      "the-field",
      "The Field: The Quest for the Secret Force of the Universe",
      "Lynne McTaggart",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: HarperCollins, 2002.",
    ),
    line(
      "chance-and-necessity",
      "Chance and Necessity: An Essay on the Natural Philosophy of Modern Biology",
      "Jacques Monod",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Alfred A Knopf, 1971.",
    ),
    line(
      "nature-of-reality",
      "The Nature of Reality: The Universe After Einstein",
      "Richard Morris",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Noonday Press, 1988.",
    ),
    line(
      "lonely-hearts",
      "Lonely Hearts of the Cosmos: The Story of the Scientific Quest for the Secret of the Universe",
      "Dennis Overbye",
      "General reading on psychology, physics, metaphysics and the like",
      "London: Pan Macmillan, 1991.",
    ),
    line(
      "synchronicity",
      "Synchronicity: The Bridge Between Matter and Mind",
      "F. David Peat",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Bantam Books, 1987.",
    ),
    line(
      "phillips-subatomic",
      "Extrasensory Perception of Subatomic Particles: Historical Evidence",
      "Stephen M. Phillips",
      "General reading on psychology, physics, metaphysics and the like",
      "Journal of Scientific Exploration 9 (1995):489-525.",
    ),
    line(
      "where-is-science-going",
      "Where is Science Going?",
      "Max Planck",
      "General reading on psychology, physics, metaphysics and the like",
      "Woodbridge, CT: Ox Bow Press 1981.",
    ),
    line(
      "conscious-universe",
      "The Conscious Universe: The Scientific Truth of Psychic Phenomena",
      "Dean Radon",
      "General reading on psychology, physics, metaphysics and the like",
      "San Francisco: HarperSanFrancisco, 1997. The surname is spelled Radon, as written.",
    ),
    line(
      "ultimate-fate",
      "The Ultimate Fate of the Universe: An Eschatological Study",
      "Martin J. Rees",
      "General reading on psychology, physics, metaphysics and the like",
      "The Observatory 89 (1969): 193.",
    ),
    line(
      "hidden-channels",
      "Hidden Channels of the Mind",
      "Louisa E. Rhine",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Warner Books, 1989.",
    ),
    line(
      "revelations",
      "Revelations: Wisdom of the Ages: Prophetic Visions and Secret Knowledge to Guide Us into the Millennium",
      "Paul Roland",
      "General reading on psychology, physics, metaphysics and the like",
      "Berkeley, CA: Ulysses Press, 1995.",
    ),
    line(
      "minds-brains-science",
      "Minds, Brains, and Science",
      "John Searle",
      "General reading on psychology, physics, metaphysics and the like",
      "Cambridge, MA: Harvard University Press, 1986.",
    ),
    line(
      "your-body-speaks",
      "Your Body Speaks Your Mind: Decoding the Emotional, Psychological, and Spiritual Messages That Underlie Illness",
      "Deb Shapiro",
      "General reading on psychology, physics, metaphysics and the like",
      "Boulder, CO: Sounds True, 2006.",
    ),
    line(
      "breaking-the-mind-barrier",
      "Breaking the Mind Barrier",
      "Todd Silver",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Simon & Schuster, 1997.",
    ),
    line(
      "modern-experiments-telepathy",
      "Modern Experiments in Telepathy",
      "S. G. Soal and F. Bateman",
      "General reading on psychology, physics, metaphysics and the like",
      "London: Faber & Faber, 1954.",
    ),
    line(
      "fourth-turning",
      "The Fourth Turning: An American Prophecy",
      "William Strauss and Neil How's",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Broadway Books, 1998. The second name is spelled Neil How's, as written.",
    ),
    line(
      "wisdom-of-crowds",
      "The Wisdom of Crowds: Why the Many Are Smarter Than the Few and How Collective Wisdom Shapes Business, Economies, Societies, and Nations",
      "James Surowiecki",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Doubleday, 2004.",
    ),
    line(
      "holographic-universe",
      "The Holographic Universe",
      "Michael Talbot",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Harper Perennial, 1992.",
    ),
    line(
      "power-of-now",
      "The Power of Now: A Guide to Spiritual Enlightenment",
      "Eckhart Tolls",
      "General reading on psychology, physics, metaphysics and the like",
      "Vancouver: Namaste Publishing, 1999. The surname is spelled Tolls, as written.",
    ),
    line(
      "mind-body-tool-kit",
      "Dr Andrew Weil's Mind-Body Tool Kit",
      "Andrew Weil",
      "General reading on psychology, physics, metaphysics and the like",
      "Boulder, Co: Sounds True, 2006.",
    ),
    line(
      "quantum-questions",
      "Quantum Questions: Mystical Writings of the World's Great Physicists",
      "Ken Wilber",
      "General reading on psychology, physics, metaphysics and the like",
      "Boston: Shambhala Publications, 1984.",
    ),
    line(
      "integral-operating-system",
      "The Integral Operating System",
      "Ken Wilber",
      "General reading on psychology, physics, metaphysics and the like",
      "Boulder, CO: Sounds True, 2005.",
    ),
    line(
      "thoughts-through-space",
      "Thoughts through Space: A Remarkable Adventure in the Realm of Mind",
      "Sir Hubert Wilkins and Harold M. Sherman",
      "General reading on psychology, physics, metaphysics and the like",
      "Charlottesville, VA: Hampton Roads Publishing Company, 2004.",
    ),
    line(
      "art-of-memory",
      "The Art of Memory",
      "Frances A. Yates",
      "General reading on psychology, physics, metaphysics and the like",
      "Chicago: University of Chicago Press, 1974.",
    ),
    line(
      "seat-of-the-soul",
      "The Seat of the Soul",
      "Gary Zukav",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Simon & Schuster, 1989.",
    ),
    line(
      "mental-radio",
      "Mental Radio",
      "Upton Sinclair",
      "General reading on psychology, physics, metaphysics and the like",
      "New York: Warner Books, 1991.",
    ),
    line(
      "indigo-children",
      "The Indigo Children: The New Kids Have Arrived",
      "Lee Carroll and Jan Tober",
      "Children and psychic ability",
      "Calsbad, CA: Hay House, 1999. The place is spelled Calsbad, as written.",
    ),
    line(
      "all-i-see",
      "All I See Is Part of Me",
      "Chara M. Curtis",
      "Children and psychic ability",
      "Bellevue, WA: Illumination Arts Publishing Company, 1994.",
    ),
    line(
      "care-and-feeding-indigo",
      "The Care and Feeding of Indigo Children",
      "Doreen Virtue",
      "Children and psychic ability",
      "Carlsbad, CA: Hay House, 2001.",
    ),
    line(
      "crystal-children",
      "The Crystal Children: A Guide to the Newest Generation of Psychic and Sensitive Children",
      "Doreen Virtue",
      "Children and psychic ability",
      "Carlsbad, CA: Hay House, 2003.",
    ),
  ];
}
